#pragma once
/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// d_iface.h: interface header file for rasterization driver modules
#ifdef GLQUAKE
#   error   GLQUAKE defined
#endif
#include "model/model.h"
#include "Triangle.h"
#include "Sprite.h"
#include "Alias.h"


#define WARP_WIDTH  (320)
#define WARP_HEIGHT (200)

#define MAX_LBM_HEIGHT (480)

typedef struct PolyDesc_s {
    int         numverts;
    float       nearzi;
    mSurface_p  pcurrentface;
    PolyVert_p  pverts;
} PolyDesc_t;


// !!! if this is changed, it must be changed in d_ifacea.h too !!!
typedef struct {
    TypeLess_ptr pskin;
    mAliasSkinDesc_p pskindesc;
    int         skinwidth;
    int         skinheight;
    mTriangle_p ptriangles;
    FinalVert_p pfinalverts;
    int         numtriangles;
    int         drawtype;
    int         seamfixupX16;
} AffineTriDesc_t;

// !!! if this is changed, it must be changed in d_ifacea.h too !!!
// typedef struct {
//     float u, v, zi, color;
// } ScreenPart_t; // ???


typedef struct {
    int     u, v;
    float   zi;
    int     color;
} zPointDesc_t;


extern int  d_spanpixcount;
extern int  r_framecount;            // sequence # of current frame since Quake started
extern bool r_drawpolys;        // 1 if driver wants clipped polygons rather than a span list
extern bool r_drawculledpolys;  // 1 if driver wants clipped polygons that have been culled by the edge list
extern bool r_worldpolysbacktofront;    // 1 if driver wants polygons delivered back to front rather than front to back
extern bool r_recursiveaffinetriangles; // true if a driver wants to use
//  recursive triangular subdivison and vertex drawing via D_PolysetDrawFinalVerts() past
//  a certain distance (normally only used by the software driver)
extern float r_aliasuvscale;    // scale-up factor for screen u and v on Alias vertices passed to driver
extern int r_pixbytes;
extern bool r_dowarp;

extern AffineTriDesc_t r_affinetridesc;
extern SpriteDesc_t r_spritedesc;
extern zPointDesc_t r_zpointdesc;
extern PolyDesc_t r_polydesc;

extern int d_con_indirect; // if 0, Quake will draw console directly to vid.buffer; if 1, Quake will
//  draw console via D_DrawRect. Must be defined by driver

extern vec3_t r_pright, r_pup, r_ppn;


void D_Aff8Patch(TypeLess_ptr pcolormap);
void D_BeginDirectRect(int x, int y, uint8_p pbitmap, int width, int height);
void D_DisableBackBufferAccess();
void D_EndDirectRect(int x, int y, int width, int height);
void D_PolysetDraw();
void D_PolysetDrawFinalVerts(FinalVert_p fv, int numverts);
void D_DrawPoly();
void D_DrawSprite();
void D_DrawSurfaces();
void D_DrawZPoint();
void D_EnableBackBufferAccess();
void D_EndParticles();
void D_Init();
void D_ViewChanged();
void D_SetupFrame();
void D_StartParticles();
void D_TurnZOn();
void D_WarpScreen();

void D_FillRect(vRect_p vrect, int color);
// void D_DrawRect();
void D_UpdateRects(vRect_p prect);

// currently for internal use only, and should be a do-nothing function in hardware drivers
// FIXME: this should go away
void D_PolysetUpdateTables();

// these are currently for internal use only, and should not be used by drivers
extern int r_skydirect;
extern uint8_p r_skysource;

// transparency types for D_DrawRect ()
typedef enum {
    DR_SOLID        = 0, // draw solid
    DR_TRANSPARENT  = 1  // draw transparent
} drawrect_t;

// !!! must be kept the same as in quakeasm.h !!!
#define TRANSPARENT_COLOR (0xFF)

extern TypeLess_ptr acolormap; // FIXME: should go away

//=======================================================================//

// callbacks to Quake

void R_DrawSurface();
void R_GenTile(mSurface_p psurf, TypeLess_ptr pdest);


// !!! if this is changed, it must be changed in d_ifacea.h too !!!
#define TURB_TEX_SIZE 64  // base turbulent texture size

// !!! if this is changed, it must be changed in d_ifacea.h too !!!
#define CYCLE       128  // turbulent cycle size

#define TILE_SIZE   128  // size of textures generated by R_GenTiledSurf

#define SKYSHIFT    7
#define SKYSIZE     (1 << SKYSHIFT)
#define SKYMASK     (SKYSIZE - 1)

extern float skyspeed, skyspeed2;

#include "qTime.h"
extern LegacyTimeDelta_t skytime;

extern int c_surf;
extern vRect_t scr_vrect;
extern uint8_p r_warpbuffer;

