#pragma once
/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#include <stdio.h>
#include "types.h"
#include "mathlib.h"
#include "link.h"
#include "pr_comp.h"    // defs shared with qcc
#include "progdefs.h"   // generated by program cdefs
#include "enginedefs.h"
// #include "server.h"

typedef union eval_s {
    string_t    string;
    float       _float;
    vec3_t       vector;
    func_t      function;
    int32_t     _int;    // VM-slot as 32-bit
    int32_t     edict;   // 32-bit byte offset from sv.edicts
} eval_t;
typedef eval_t* eval_p;

#define MAX_ENT_LEAFS (16)
typedef struct edict_s {
    qboolean        free;
    link_t          area;       // linked to a division node or leaf
    int32_t         num_leafs;
    int16_t         leafnums[MAX_ENT_LEAFS];
    EntityState_t   baseline;
    float           freetime;   // sv.time when the object was freed
    entvars_t       v;          // C exported fields from progs
    // other fields from progs come immediately after
} edict_t;
typedef edict_t* edict_p;
#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l,edict_t,area)

//============================================================================

extern dprograms_p  progs;
extern dfunction_p  pr_functions;
extern cstring      pr_strings;
extern ddef_p       pr_globaldefs;
extern ddef_p       pr_fielddefs;
extern dstatement_p pr_statements;
extern globalvars_p pr_global_struct;
extern float_p      pr_globals;     // same as pr_global_struct
extern int32_t      pr_edict_size;  // in bytes

//============================================================================

void PR_Init();

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs();

void PR_Profile_f();

edict_p  ED_Alloc();
void ED_Free(edict_p ed);

cstring ED_NewString(cstring string);
// returns a copy of the string allocated from the server's string heap

void ED_Print(edict_p ed);
void ED_Write(FILE* f, edict_p ed);
cstring ED_ParseEdict(cstring data, edict_p ent);

void ED_WriteGlobals(FILE* f);
void ED_ParseGlobals(cstring data);

void ED_LoadFromFile(cstring data);
bool ED_ParseEpair(typeless_ptr base, ddef_p key, cstring s);

#if 0
// define EDICT_NUM(n) ((edict_p )(sv.edicts+ (n)*pr_edict_size))
// define NUM_FOR_EDICT(e) (((uint8_p)(e) - sv.edicts)/pr_edict_size)
#else
edict_p EDICT_NUM(int32_t n);
int32_t NUM_FOR_EDICT(edict_p e);
#   define NEXT_EDICT(e)        ((edict_p)((uint8_p)(e) + pr_edict_size))
#   define PROG_EDICT_BASE      ((uint8_p)sv.edicts)
#   define PROG_TO_EDICT(ofs)   ((edict_p)(PROG_EDICT_BASE + (uint32_t)(ofs)))
#   define EDICT_TO_PROG(e)     ((uint32_t)((uint8_p)(e) - PROG_EDICT_BASE))
#endif
// #define NEXT_EDICT(e)       ((edict_p )( (uint8_p)(e) + pr_edict_size))

#if 0
#define EDICT_TO_PROG(e)    ((uint8_p)e - (uint8_p)sv.edicts)
#define PROG_TO_EDICT(e)    ((edict_p )((uint8_p)sv.edicts + e))
#else
// #   define EDICT_TO_PROG(e)    PR_OfsFromEdict((e))          /* -> uint32 offset */
// #   define PROG_TO_EDICT(o)    PR_EdictFromOfs((uint32_t)(o))
#endif

//============================================================================

#if 0
#define G_FLOAT(o)      (pr_globals[o])
#define G_INT(o)        (*(int*)&pr_globals[o])
#define G_EDICT(o)      ((edict_p )((uint8_p)sv.edicts+ *(int*)&pr_globals[o]))
#define G_EDICTNUM(o)   NUM_FOR_EDICT(G_EDICT(o))
#define G_VECTOR(o)     (&pr_globals[o])
#define G_STRING(o)     (pr_strings + *(string_t*)&pr_globals[o])
#define G_FUNCTION(o)   (*(func_t*)&pr_globals[o])
#else
#   define G_FLOAT(o)      (pr_globals[(o)])
#   define G_INT(o)        (*(int32_t*)&pr_globals[(o)])
#   define G_VECTOR(o)     (&pr_globals[(o)])
#   define G_FUNCTION(o)   (*(func_t*)&pr_globals[(o)])

// безопасное взятие строки: проверяем, что индекс в пределах string-table
static inline cstring PR_GetStringSafe(uint32_t str_ofs) {
    // if (
    //     // (str_ofs < 0) ||
    //     ((uint32_t)str_ofs >= (uint32_t)progs->num_strings)
    //     ) {
    //     printf("ACHTUNG!!! %u/%u\n", (unsigned)str_ofs, (unsigned)progs->num_strings);
    //     // return ""; // или вернуть специальную заглушку, чтобы не падать
    // }
    return pr_strings + str_ofs;
}
#   define G_STRING(o)     PR_GetStringSafe(*(string_t*)&pr_globals[(o)])

// edict хранится как 32-битный байтовый офсет от sv.edicts
#   define G_EDICT(o)      PROG_TO_EDICT((uint32_t)G_INT((o)))
#   define G_EDICTNUM(o)   NUM_FOR_EDICT(G_EDICT((o)))
#endif

#if 0
#define E_FLOAT(e,o)    (((float_p)&e->v)[o])
#define E_INT(e,o)      (*(int*)&((float_p)&e->v)[o])
#define E_VECTOR(e,o)   (&((float_p)&e->v)[o])
#define E_STRING(e,o)   (pr_strings + *(string_t*)&((float_p)&e->v)[o])
#else
#   define E_FLOAT(e,o)    (((float_p)&(e)->v)[(o)])
#   define E_INT(e,o)      (*(int32_t*)&((float_p)&(e)->v)[(o)])
#   define E_VECTOR(e,o)   (&((float_p)&(e)->v)[(o)])
#   define E_STRING(e,o)   PR_GetStringSafe(*(string_t*)&((float_p)&(e)->v)[(o)])
#endif

extern int32_t  type_size[8];

typedef void (*builtin_t)();
extern builtin_t* pr_builtins;
extern int32_t pr_numbuiltins;

extern int32_t pr_argc;

extern qboolean pr_trace;
extern dfunction_p pr_xfunction;
extern int32_t pr_xstatement;

extern uint16_t pr_crc;

void PR_RunError(cstring error, ...);

void ED_PrintEdicts();
void ED_PrintNum(int32_t ent);

eval_t* GetEdictFieldValue(edict_p ed, cstring field);

