#pragma once
/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#include "pr_comp.h"			// defs shared with qcc
#include "progdefs.h"			// generated by program cdefs

typedef union eval_s {
	string_t    string;
	float       _float;
	float       vector[3];
	func_t      function;
	int         _int;
	int         edict;
} eval_t;
typedef eval_t* eval_p;

#define	MAX_ENT_LEAFS	16
typedef struct edict_s {
	qboolean	free;
	link_t		area;				// linked to a division node or leaf

	int			num_leafs;
	int16_t		leafnums[MAX_ENT_LEAFS];

	entity_state_t	baseline;

	float		freetime;			// sv.time when the object was freed
	entvars_t	v;					// C exported fields from progs
	// other fields from progs come immediately after
} edict_t;
typedef edict_t* edict_p;
#define	EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l,edict_t,area)

//============================================================================

extern	dprograms_p    progs;
extern	dfunction_p    pr_functions;
extern	cstring         pr_strings;
extern	ddef_p         pr_globaldefs;
extern	ddef_p         pr_fielddefs;
extern	dstatement_p    pr_statements;
extern	globalvars_t* pr_global_struct;
extern	float* pr_globals;			// same as pr_global_struct

extern	int				pr_edict_size;	// in bytes

//============================================================================

void PR_Init();

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs();

void PR_Profile_f();

edict_p  ED_Alloc();
void ED_Free(edict_p ed);

cstring ED_NewString(cstring string);
// returns a copy of the string allocated from the server's string heap

void ED_Print(edict_p ed);
void ED_Write(FILE* f, edict_p ed);
cstring ED_ParseEdict(cstring data, edict_p ent);

void ED_WriteGlobals(FILE* f);
void ED_ParseGlobals(cstring data);

void ED_LoadFromFile(cstring data);

//define EDICT_NUM(n) ((edict_p )(sv.edicts+ (n)*pr_edict_size))
//define NUM_FOR_EDICT(e) (((byte *)(e) - sv.edicts)/pr_edict_size)

edict_p EDICT_NUM(int n);
int NUM_FOR_EDICT(edict_p e);

#define	NEXT_EDICT(e) ((edict_p )( (byte *)e + pr_edict_size))

#define	EDICT_TO_PROG(e) ((byte *)e - (byte *)sv.edicts)
#define PROG_TO_EDICT(e) ((edict_p )((byte *)sv.edicts + e))

//============================================================================

#define	G_FLOAT(o) (pr_globals[o])
#define	G_INT(o) (*(int *)&pr_globals[o])
#define	G_EDICT(o) ((edict_p )((byte *)sv.edicts+ *(int *)&pr_globals[o]))
#define G_EDICTNUM(o) NUM_FOR_EDICT(G_EDICT(o))
#define	G_VECTOR(o) (&pr_globals[o])
#define	G_STRING(o) (pr_strings + *(string_t *)&pr_globals[o])
#define	G_FUNCTION(o) (*(func_t *)&pr_globals[o])

#define	E_FLOAT(e,o) (((float*)&e->v)[o])
#define	E_INT(e,o) (*(int *)&((float*)&e->v)[o])
#define	E_VECTOR(e,o) (&((float*)&e->v)[o])
#define	E_STRING(e,o) (pr_strings + *(string_t *)&((float*)&e->v)[o])

extern	int		type_size[8];

typedef void (*builtin_t)();
extern	builtin_t* pr_builtins;
extern int pr_numbuiltins;

extern int		pr_argc;

extern	qboolean	pr_trace;
extern	dfunction_p pr_xfunction;
extern	int			pr_xstatement;

extern	uint16_t		pr_crc;

void PR_RunError(cstring error, ...);

void ED_PrintEdicts();
void ED_PrintNum(int ent);

eval_t* GetEdictFieldValue(edict_p ed, cstring field);

