$(eval INCLUDES += $(STMSRC_DIR)/Drivers/CMSIS/Device/ST/STM32F7xx/Include)
$(eval INCLUDES += $(STMSRC_DIR)/Drivers/CMSIS/Include)
$(eval HAL_DIR := $(STMSRC_DIR)/Drivers/STM32F7xx_HAL_Driver)
    $(eval INCLUDES += $(HAL_DIR)/Inc)
    $(eval INCLUDES += $(HAL_DIR)/Inc/Legacy)
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_adc.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_adc_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_cec.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_cortex.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_crc.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_crc_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_dma.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_dma2d.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_dma_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_dsi.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_eth.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_exti.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_flash.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_flash_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_gpio.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_i2c.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_i2c_ex.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_iwdg.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_ltdc.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_ltdc_ex.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_mmc.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_nand.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_nor.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_pcd.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_pcd_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_pwr.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_pwr_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_qspi.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_rcc.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_rcc_ex.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_rtc.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_rtc_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_sai.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_sai_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_sd.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_sdram.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_spdifrx.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_spi.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_spi_ex.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_sram.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_tim.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_tim_ex.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_uart.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_uart_ex.c
#     SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_hal_wwdg.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_ll_fmc.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_ll_sdmmc.c
    SRC_LIST += $(HAL_DIR)/Src/stm32f7xx_ll_usb.c
