#pragma once

#include "link.h"
#include "EntityState.h"
#include "pr_comp.h"    // defs shared with qcc
#include "progdefs.h"   // generated by program cdefs

#define MAX_ENT_LEAFS (16)
typedef struct edict_s {
    bool            free;
    link_t          area;       // linked to a division node or leaf
    int32_t         num_leafs;
    int16_t         leafnums[MAX_ENT_LEAFS];
    EntityState_t   baseline;
    float           freetime;   // sv.time when the object was freed
    entvars_t       v;          // C exported fields from progs
    // other fields from progs come immediately after
} edict_t;
typedef edict_t* edict_p;
#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l, edict_t, area)