#pragma once
/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#include <stdio.h>
#include "pr_comp.h"    // defs shared with qcc
#include "progdefs.h"   // generated by program cdefs

#define MAX_FIELD_LEN (64)
#define GEFV_CACHESIZE (2)

typedef int32_t qVmString_t;    // should be signed!!! it was [string_t] from "pr_comp.h"

typedef struct {
    dDef_p  pcache;
    char    field[MAX_FIELD_LEN];
} gefv_cache;

extern gefv_cache gefvCache[GEFV_CACHESIZE];
//============================================================================
typedef void (*builtin_t)();
extern builtin_t* pr_builtins;
extern int32_t    pr_numbuiltins;

extern dFunction_p  pr_functions;
// extern cString      pr_strings; // should be static
extern dDef_p       pr_globaldefs;
extern dDef_p       pr_fielddefs;
extern dStatement_p pr_statements;

extern int32_t      pr_argc;        // number of op_call
extern bool         pr_trace;
extern dFunction_p  pr_xFunction;
// extern int32_t      pr_xstatement;
extern uint16_t     pr_crc;

extern dprograms_p  progs;

extern int32_t      current_skill;  // skill level for currently loaded level (in case the user changes the cvar while the level is running, this reflects the level actually in use)

//============================================================================
#ifdef __cplusplus
extern "C" {
#endif

    void PR_Init();

    void PR_LoadProgs();
    void PR_ClearAppStrings();

    void PR_ExecuteProgram(func_t fnum);

    cString PR_ValueString(etype_t type, eval_p val);
    cString PR_UglyValueString(etype_t type, eval_p val);

    void PR_Profile_f();

// #   define G_FUNCTION(o)    (*(func_t*)&pr_globals[(o)])

#   define G_FLOAT(o)       (pr_globals[(o)])
#   define G_INT(o)         (*(int32_p)&pr_globals[(o)])
#   define G_VECTOR(o)      (&pr_globals[(o)])
#   define G_STRING(o)      PR_GetQString(*(qVmString_t*)&pr_globals[(o)])

// #   define E_FLOAT(e,o)     (((float_p)&(e)->v)[(o)])
// #   define E_INT(e,o)       (*(int32_p)&((float_p)&(e)->v)[(o)])
// #   define E_VECTOR(e,o)    (&((float_p)&(e)->v)[(o)])
#   define E_STRING(e,o)    PR_GetQString(*(qVmString_t*)&((float_p)&(e)->v)[(o)])

    qVmString_t PR_SetQString(cString str);
    cString PR_GetQString(qVmString_t offs);

    void PR_RunError(cString error, ...);

#ifdef __cplusplus
}
#endif