#pragma once
/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#include <stdio.h>
#include "pr_def.h"    // defs shared with qcc
#include "pr_qString.h"
#include "progdefs.h"   // generated by program cdefs


#define MAX_FIELD_LEN (64)
#define GEFV_CACHESIZE (2)

typedef struct {
    dDef_p  pcache;
    char    field[MAX_FIELD_LEN];
} gefv_cache;

extern gefv_cache gefvCache[GEFV_CACHESIZE];

//============================================================================

extern int32_t      pr_argc;        // number of op_call
extern bool         pr_trace;
extern uint16_t     pr_crc;

extern int32_t      current_skill;  // skill level for currently loaded level (in case the user changes the cvar while the level is running, this reflects the level actually in use)

//============================================================================
#ifdef __cplusplus
extern "C" {
#endif

    void PR_Init();
    void PR_LoadProgs();
    void PR_ExecuteProgram(func_t fnum);
    void PR_Profile_f();
    void PR_RunError(cString error, ...);

#ifdef __cplusplus
}
#endif