#pragma once
/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#include <stdio.h>
#include "pr_comp.h"    // defs shared with qcc
#include "progdefs.h"   // generated by program cdefs
#include "Edict.h"

//============================================================================
typedef void (*builtin_t)();
extern builtin_t* pr_builtins;

extern dFunction_p  pr_functions;
extern cString      pr_strings;
extern dDef_p       pr_globaldefs;
extern dDef_p       pr_fielddefs;
extern dStatement_p pr_statements;
extern globalvars_p pr_global_struct;
extern float_p      pr_globals;     // same as pr_global_struct
extern uint32_t     pr_edict_size;  // in bytes
extern int32_t      pr_numbuiltins;
extern int32_t      pr_argc;
extern bool         pr_trace;
extern dFunction_p  pr_xfunction;
extern int32_t      pr_xstatement;
extern uint16_t     pr_crc;

extern dprograms_p  progs;
extern int32_t      current_skill;  // skill level for currently loaded level (in case the user changes the cvar while the level is running, this reflects the level actually in use)

//============================================================================
#ifdef __cplusplus
extern "C" {
#endif

    void PR_Init();

    void PR_ExecuteProgram(func_t fnum);
    void PR_LoadProgs();

    void PR_Profile_f();

    edict_p ED_Alloc();
    void ED_Free(edict_p ed);

    cString ED_NewString(cString string);   // returns a copy of the string allocated from the server's string heap

    void ED_Print(edict_p ed);
    void ED_Write(FILE* f, edict_p ed);
    cString ED_ParseEdict(cString data, edict_p ent);

    void ED_WriteGlobals(FILE* f);
    void ED_ParseGlobals(cString data);

    void ED_LoadFromFile(cString data);
    bool ED_ParseEpair(TypeLess_ptr base, dDef_p key, cString s);

    edict_p EDICT_NUM(uint32_t n);
    uint32_t NUM_FOR_EDICT(edict_p e);

#   define NEXT_EDICT(e)        ((edict_p)((uint8_p)(e) + pr_edict_size))
#   define PROG_EDICT_BASE      ((uint8_p)sv.edicts)
#   define PROG_TO_EDICT(ofs)   ((edict_p)(PROG_EDICT_BASE + (uint32_t)(ofs)))
#   define EDICT_TO_PROG(e)     ((int32_t)((uint8_p)(e) - PROG_EDICT_BASE))

#   define G_FLOAT(o)       (pr_globals[(o)])
#   define G_INT(o)         (*(int32_t*)&pr_globals[(o)])
#   define G_VECTOR(o)      (&pr_globals[(o)])
#   define G_FUNCTION(o)    (*(func_t*)&pr_globals[(o)])
#   define G_EDICT(o)       PROG_TO_EDICT((uint32_t)G_INT((o)))
#   define G_EDICTNUM(o)    NUM_FOR_EDICT(G_EDICT((o)))

#   define E_FLOAT(e,o)     (((float_p)&(e)->v)[(o)])
#   define E_INT(e,o)       (*(int32_t*)&((float_p)&(e)->v)[(o)])
#   define E_VECTOR(e,o)    (&((float_p)&(e)->v)[(o)])
#   define G_STRING(o)      PR_GetStringSafe(*(string_t*)&pr_globals[(o)])
#   define E_STRING(e,o)    PR_GetStringSafe(*(string_t*)&((float_p)&(e)->v)[(o)])

    static inline cString PR_GetStringSafe(int32_t str_ofs) { return pr_strings + str_ofs; }
    void PR_RunError(cString error, ...);
    void ED_PrintEdicts();
    void ED_PrintNum(uint32_t ent);

    eval_p GetEdictFieldValue(edict_p ed, cString field);

#ifdef __cplusplus
}
#endif